### ISSUE TITLE
Xed won't open file

### ISSUE THREAD

**Issue by muzena** [linuxmint/xed#278] opened 2019-03-13 18:51 UTC
```
 * Xed version (xed 2.02)
 * Distribution - (Mint 19.1 Cinnamon)
```

**Issue**
Xed won't open this type of file:
[m.tvprofil.net_.ini.zip](https://github.com/linuxmint/xed/files/2963106/m.tvprofil.net_.ini.zip)

This is error when I try to start from terminal:
(xed:5895): Gdk-CRITICAL **: 19:44:49.660: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
**
GtkSourceView:ERROR:gtksourcecontextengine.c:5543:update_syntax: assertion failed: (g_slist_length (ce->priv->invalid) <= 1)
Prekinut (jezgra izbačena)

**Comment by leigh123linux** [comment] 2019-03-13 19:49
Why do you expect a text editor to open compressed archive?

**Comment by leigh123linux** [comment] 2019-03-13 19:58
I can reproduce the issue here on the uncompressed file

```
unzip m.tvprofil.net_.ini.zip
xed m.tvprofil.net_.ini
**
GtkSourceView:ERROR:gtksourcecontextengine.c:5543:update_syntax: assertion failed: (g_slist_length (ce->priv->invalid) <= 1)
Aborted (core dumped)

```
$ file m.tvprofil.net_.ini
m.tvprofil.net_.ini: HTML document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
```

vi can open the file ok.

**Comment by JosephMcc** [comment] 2019-04-14 08:02
I can reproduce this not only in xed but also gedit. It looks like it's an issue with gtksourceview which isn't something we control. This problem should probably be reported to them.

**Comment by icarter09** [comment] 2019-12-14 21:21
Created a ticket for the GtkSourceView team and linked back to this ticket.

https://gitlab.gnome.org/GNOME/gtksourceview/issues/99

**Comment by icarter09** [comment] 2019-12-15 04:07
Received some feedback from the Gnome team on the ticket I created...

_Duplicate of #30 (closed) unless you can provide GtkSourceView version information showing that patch was included in your builds._

Can someone point in the right direction to finding this information? Thanks.

**Comment by JosephMcc** [comment] 2020-09-11 08:30
This seems to fixed on git master using the new GtkSourceView 4

**Closed by JosephMcc** 2020-09-11 08:30 UTC
