### ISSUE TITLE
Xed 1.4.4 not autoclosing when file changes are saved

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/xed#146] opened 2017-07-02 21:57 UTC
Linux Mint 18.2 beta Cinnamon 64 Bit (shouldn't matter here).

Say you have a file opened (so filename exists), where you have write permission and you have changed something in the content, but forgotten to save it. Now you quit xed. Because of the changes xed asks you how to proceed: (not) saving, aborting. You click on "save".

Expected: The file gets saved and xed closes.

Actually the file gets saved but the application stays open and the command to quit must get selected again.
This does happen regardless, if you use the mouse for quitting and clicking the save button or you do this via keyboard (alt-F4 -> alt-s).

**Comment by JosephMcc** [comment] 2017-07-02 22:39
Already aware of this one from multiple sources :)

**Comment by KirkM** [comment] 2017-07-16 13:06
Xed was upgraded to version to version 1.4.5 and now 1.4.6 and the bug still persists. Just FYI.

**Comment by spsf64** [comment] 2017-07-19 13:55
Same problem here, version 1.4.6, using in archlinux

**Comment by oblongau** [comment] 2017-08-17 23:23
Problem confirmed in Linux Mint 18.2 64 bit, MATE, Xed 1.4.6.

**Comment by TugaPowerROM** [comment] 2017-09-30 13:20
And still present the bug

**Comment by happyniko** [comment] 2017-11-26 12:17
This issue is a problem in the Mint System not of the editor itself! The problem with the closing is the same with Xed version 1.60, Gedit 3.18.3 and Kate 15.12.3 and exists since 18.2! I`m really surprised that no one has noticed this and solved it. How can this be? Poor souls who use the editor for programming...

**Comment by TugaPowerROM** [comment] 2017-11-26 12:26
Seems no one read the github issues beside we users

**Comment by JosephMcc** [comment] 2017-11-26 12:37
> Seems no one read the github issues beside we users

You do see that this was tagged as a bug that can be reproduced correct?

The problem is in xed/gtksourceview. I have this issue fixed locally but the changes can't be merged until we are ready to move to gtk3.22.

**Comment by TugaPowerROM** [comment] 2017-11-26 12:54
tagged in 3 Jul , we all can see, but a thing like this that is so annoying is still not fixed.

**Comment by happyniko** [comment] 2017-11-26 13:02
@JosephMcc 

Thanks for the immediate reply and your efforts for improvement! Will this issue will also be fixed for Kate and Gedit editors? Or does the xed/gtksourceview affect the Xed editor only? This is my point of interest.

**Comment by JosephMcc** [comment] 2017-11-26 20:09
@happyniko newer versions of gedit don't have this issue. I have no idea about Kate. Isn't it a KDE app? If that's the case it's probably totally unrelated.

@TugaPowerROM I understand. I had limited time this dev cycle and while this is clearly a bug, it's a bug of inconvenience. What would be much worse is closing the window without the files being properly saved. I wanted to tackle this when I had time to test it properly.

**Comment by dodona2** [comment] 2017-11-26 21:09
'How can this be? Poor souls who use the editor for programming...'
thousand of programmers using vi or a vi clone all without autoclosing.

**Comment by oblongau** [comment] 2017-11-27 00:18
The problem is still in Mint 18.3 MATE 64 beta.

**Closed** 2018-03-09 15:11 UTC
Labels: BUG REPRODUCED, Ready
