### ISSUE TITLE
opening text files with one or more long lines makes the application unresponding

### ISSUE THREAD

**Issue by dferl** [linuxmint/xed#584] opened 2023-05-27 08:11 UTC
```
 * Xed version (3.2.8)
 * Distribution - (Linux Mint 21.1, Vera...)
```

**opening text files with one or more long lines makes the application unresponding**

I was trying to edit a file representing a BTREE structure and some of the lines I realised were very, very long (15000 char long). I realise too the little use of having a line so long opened in a file editor because it would be difficultt to read anyway, but I noticed that ,for example, NOTEPAD++ opens the long line without any problem.

Anyway, I find the application very useful for developing and I take this opportunity for thank you for your work.

**Steps to reproduce**
Create a .txt file with at least one very long line (as I said in my case 15000 char long); I used the no word wrap view mode.

**Expected behaviour**
The application should not get in an unresponding state.

**Other information**

**Comment by leigh123linux** [comment] 2023-05-27 09:36
Duplicate of #500

**Closed by leigh123linux** 2023-05-27 09:36 UTC
