### ISSUE TITLE
Enchant naming change breaks build

### ISSUE THREAD

**Issue by ion201** [linuxmint/xed#210] opened 2018-01-27 02:56 UTC
Arch recently got enchant 2.2.1 which changed "enchant" to "enchant-2" in the filesystem. This breaks the xed 1.6.3 build like so:

```
...
checking for enchant >= 1.2.0... no

configure: error: Enchant library not found or too old. Use --disable-
spell to build without spell plugin.
 ~ % pacman -Qi enchant 
Name            : enchant
Version         : 2.2.1-1
Description     : A wrapper library for generic spell checking
Architecture    : x86_64
URL             : https://abiword.github.io/enchant/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : aspell  hunspell  hspell  libvoikko  glib2
Optional Deps   : None
Required By     : webkit2gtk  xed
Optional For    : hexchat
Conflicts With  : None
Replaces        : None
Installed Size  : 140.00 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon 15 Jan 2018 11:09:53 AM CST
Install Date    : Fri 26 Jan 2018 07:36:23 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

 ~ % pacman -Ql enchant 
enchant /usr/
enchant /usr/bin/
enchant /usr/bin/enchant-2
enchant /usr/bin/enchant-lsmod-2
enchant /usr/include/
enchant /usr/include/enchant-2/
enchant /usr/include/enchant-2/enchant++.h
enchant /usr/include/enchant-2/enchant-provider.h
enchant /usr/include/enchant-2/enchant.h
enchant /usr/lib/
enchant /usr/lib/enchant-2/
enchant /usr/lib/enchant-2/enchant_aspell.so
enchant /usr/lib/enchant-2/enchant_hspell.so
enchant /usr/lib/enchant-2/enchant_hunspell.so
enchant /usr/lib/enchant-2/enchant_voikko.so
enchant /usr/lib/libenchant-2.so
enchant /usr/lib/libenchant-2.so.2
enchant /usr/lib/libenchant-2.so.2.2.1
enchant /usr/lib/pkgconfig/
enchant /usr/lib/pkgconfig/enchant-2.pc
enchant /usr/share/
enchant /usr/share/enchant/
enchant /usr/share/enchant/enchant.ordering
enchant /usr/share/man/
enchant /usr/share/man/man1/
enchant /usr/share/man/man1/enchant-2.1.gz
enchant /usr/share/man/man1/enchant-lsmod-2.1.gz
```

And here is the patch we are using in arch. I assume not appropriate for distros with more mixed versions, but worth pointing out:

    sed -i 's/, enchant/, enchant-2/' configure.ac

**Comment by JosephMcc** [comment] 2018-01-27 19:57
Thanks. As far as I can tell this isn't the case currently in Ubuntu Bionic or Debian Stretch which are our two main targets for the next couple years. Both still have enchant 1.6. Unless someone wants to submit some sort of fix that will make it work for both you will probably have to continue to patch this on your end for arch.

There was another breakage caused by the newer enchant versions that should be fixed in xed 1.8 here: https://github.com/linuxmint/xed/pull/196/commits/9833abf9b0352ac4347636bafc0693b5d9ee9d1d

**Closed by JosephMcc** 2018-01-27 19:57 UTC
