### ISSUE TITLE
occational xed hang when attempting Edit->"Insert Date and Time..."

### ISSUE THREAD

**Issue by LarryAT** [linuxmint/xed#162] opened 2017-08-30 09:54 UTC
```
 * Xed version xed - Version 1.4.6 and 
 * Xed version xed - Version 1.2.2
 * Distribution - (Mint 18.2 sonya) and
 * Distribution - (Mint 18.1 serena)
```

**Issue**
Twice with xed 1.2.2 and once with xed 1.4.6, attempting Edit->"Insert Date and Time..." caused a hang.  No xed controls worked. Window exit worked.

Most times, there were no problems with Edit -> "Insert Date and Time..."

I have never had a problem with gedit Tools -> "Insert Date and Time..." 

**Steps to reproduce**
Each time, I'd done the following:
New File.
Type a Line or two
Triple-mouse-one select top line
CTRL-C copy the selected top line
CTRL-SHIFT-S Save As ... 
CTRL-V paste the copied first line into the saved file name.
ENTER to save the file.
lots of typing, pasting, last paste being hundreds of lines.
ENTER
ENTER
UP-ARROW
Edit -> "Insert Date and Time..."  
====> HANG, unable to do anything with xed window but terminate it.

**Expected behaviour**
The initial (default) date time format text should be inserted. as normal, without a hang.

**Other information**
This has happened twice with xed 1.2.2 and once with xed 1.4.6, but since I switched to gedit, didn't get repeatability. 
I have tried to reproduce this problem several times this evening, after upgrading to xed 1.4.6, without problems, so i don't know an exact sequence to cause the hang. 

Very Sorry :(

**Comment by LarryAT** [comment] 2017-08-30 11:11
I managed to reproduce this once.

I had started 'xed filename' in a terminal window.

When xed hung, just after clicking Edit -> "Insert Date and Time..." after some pastes in a new file
there was no output in the terminal window and nothing was responding and xed process was in "poll_s" state, until:

While the xed was still hung, I typed CTRL-Z in the terminal window (e.g. like kill -STOP <term pid>) and typed 'bg<return> (like kill -CONT with diddled stdin/stdout)  in the terminal window. Whereupon i took a look at the xed page, and the date and time text had been entered and xed was working again.

**Comment by JosephMcc** [comment] 2018-02-12 02:29
I've been unable to reproduce this here which leaves me without much of a way to troubleshoot fixing it. If you make sure you have the xed-dbg package installed you can run xed with gdb and see if you can find out where the issue is occurring. I'm closing this until I can get more info to go on.

**Closed by JosephMcc** 2018-02-12 02:29 UTC
Labels: BUG

**Comment by LarryAT** [comment] 2018-02-12 05:13
Joseph,
Since reporting the intermittent problem, I modified my behavior when using Insert Date & Time:
• I type two Enter's and an UpArrow, 

• and, I Save the file before using the plugin.
I have not experienced any crashes since I began using the above "magical" pre-use steps. I say "magically" because I have no definitive algorithm to cause the crash and no proper diagnosis.
I picked the above prophylaxis because the problem always occurred after Pasting a huge block of text which might not end with a line break. So I ensure the insert occurs on an empty line and whatever normalization/cleanup which can be done after saving the file has been done. Also, if a crash were to re-occur, nothing has been lost but time.
Thank you for considering the defect report. 
If it happens again, I'll try further diagnosis. 
-- Larry 
 
  On Sun, Feb 11, 2018 at 18:29, JosephMcc<notifications@github.com> wrote:   
I've been unable to reproduce this here which leaves me without much of a way to troubleshoot fixing it. If you make sure you have the xed-dbg package installed you can run xed with gdb and see if you can find out where the issue is occurring. I'm closing this until I can get more info to go on.
