### ISSUE TITLE
Ctrl+N (new document) only works when files are open

### ISSUE THREAD

**Issue by spike200a** [linuxmint/xed#598] opened 2023-08-10 22:57 UTC
```
 * Xed version (xed --version) 3.4.3
 * Distribution - (Linux Mint 21.2 Cinnamon)
```

**Issue**
See issue title

**Steps to reproduce**
Press Ctrl+N when no files are opened

**Expected behaviour**
Open a new empty document

**Other information**

**Comment by BanceDev** [comment] 2024-06-04 20:41
Followed steps to reproduce and Ctrl+N does in fact open a new file when no files are opened, this issue can be closed.

**Comment by JosephMcc** [comment] 2024-06-05 10:33
> Followed steps to reproduce and Ctrl+N does in fact open a new file when no files are opened, this issue can be closed.

Just tried and it works for me as well. So closing.

**Closed by JosephMcc** 2024-06-05 10:33 UTC
