### ISSUE TITLE
Cannot load large files

### ISSUE THREAD

**Issue by mcarans** [linuxmint/xed#29] opened 2016-07-25 13:29 UTC
When I try to load a 100Mb file, Xed on Mint 18 hangs. GEdit 2 on Mint 17.3 works fine. GEdit 3 on Mint 18 works fine.

An example of such a file is:
[https://data.humdata.org/dataset/3e4a097f-c4e0-410a-b96a-e2d2253e2902/resource/fcc91212-31ab-40d9-8f36-3ef9ea25abc7/download/UG15_hhld.csv](https://data.humdata.org/dataset/3e4a097f-c4e0-410a-b96a-e2d2253e2902/resource/fcc91212-31ab-40d9-8f36-3ef9ea25abc7/download/UG15_hhld.csv)

**Comment by Cos-mo** [comment] 2016-08-29 11:17
I confirm partially.

xed needs more than a minute to load the file, whereas in gedit2 the file gets loaded in between of about 10 seconds.

Furthermore gedit2 shows in this case a progress indicator, whereas xed shows nothing.

Another note: If I close xed with this file opened (without having done any changes in the file), xed needs more than 30 seconds to close, sometimes it does not close at all, but a dialog appears which offers to force quit.

**Comment by Vahan86** [comment] 2016-09-26 17:43
Tried to open the file posted by @mcarans. After approx 4 minutes of waiting the following dialog window appeared:

![untitled](https://cloud.githubusercontent.com/assets/12819058/18845283/2e328b16-8432-11e6-84d1-75259098fa64.png)

**Comment by ocafebabe** [comment] 2016-10-06 22:37
+1

**Comment by JosephMcc** [comment] 2016-12-11 18:09
So the file loads for me but it took forever and pushed xed up to 4gb of memory usage. I had the same issue as you guys trying to close it.

**Comment by JosephMcc** [comment] 2017-02-10 10:40
The issue with opening large files is fixed now in git master. This particular file still has an issue when you first load it. It contains thousands of strings and the first time you open it, it will be recognized as a .csv and the string will be highlighted. This causes memory use issues but I don't think it's on our side. I can reproduce the same issue in gedit and it looks like a problem in GtkSourceView.

Since the loading is async and won't block the interface you can simply change it's type to plain text  while it's loading as a workaround which will get around the issue.

**Closed by JosephMcc** 2017-02-10 10:40 UTC
Labels: BUG REPRODUCED

**Comment by mcarans** [comment] 2017-02-10 12:28
@JosephMcc  Does the particular file cause issues on both GEdit 2 and GEdit 3 for you?

**Comment by JosephMcc** [comment] 2017-02-10 12:31
Only tested on Gedit 3.18. It's hard to compare version2 vs. 3 because of changes in the underlying version of libraries like gtk involved.

**Comment by mcarans** [comment] 2017-02-10 12:39
@JosephMcc For me it loaded in GEdit 3. Does the file eventually load on GEdit 3 for you or does it fail or hang? This is not clear from your comment from 2 hours ago. Is the behaviour exactly the same with Xed?

Thanks for looking at this issue.

**Comment by JosephMcc** [comment] 2017-02-10 12:43
Yes the file loads fine now in xed. If you open system monitor with the file open and the syntax highlighting enabled you will notice it using large amounts of memory. I can reproduce the same issue in Gedit3.18. Setting it to "Plain text" solves the issue in both Xed and Gedit.

**Comment by mcarans** [comment] 2017-02-10 12:44
Great, thanks a lot!
