### ISSUE TITLE
When hovering on tabs Mouse wheel does not scroll through them

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#383] opened 2020-06-01 16:16 UTC
```
 * Xed version (2.0.2)
 * Distribution - (Mint 19.2 MATE)
```

**Issue**
The mouse wheel to scroll tabs does not function if you are hovering over tabs, only elsewhere in the tab header

**Steps to reproduce**
enable mousewheel to scroll tabs option

**Expected behaviour**
tabs should scroll regardless of pointer position in the tab bar

**Other information**
similar issue : https://github.com/linuxmint/xed/issues/380

**Comment by icarter09** [comment] 2020-06-14 16:12
xed version 2.6.0
Mint 19.3 Cinnamon

I'm not able to reproduce this issue. Mouse wheel scrolls through tabs when I hover over them after enabling `Allow mouse wheel scrolling to change tabs` .

@calexil can you retest this issue after upgrading to the latest version of xed? Thanks.

**Comment by calexil** [comment] 2020-06-15 18:59
dumb question, whats the best way to do that without upgrading my whole system

**Comment by calexil** [comment] 2020-06-15 19:22
This issue is only on 2.0.2 which is the 'stable' version on mint 19.2

**Comment by icarter09** [comment] 2020-06-16 03:02
@calexil thanks for the update. I'm going to close this issue since it has been resolved on Mint 19.3.

**Closed by icarter09** 2020-06-16 03:02 UTC
