### ISSUE TITLE
Font size < 12 produces jumping lines when the last character is removed

### ISSUE THREAD

**Issue by dancesWithBugs** [linuxmint/xed#432] opened 2020-12-28 01:01 UTC
```
 * xed - Version 2.8.3
 * Linux Mint 20.1 Cinnamon
```

**Issue**

When the font size is set to lower than 12 (e.g. the default of 10), removing the last character from a line makes all lines below jump up a few pixels. It looks like this:

![xed-issue](https://user-images.githubusercontent.com/75453205/103183012-278e1900-48b0-11eb-90ab-43cdb4ed741f.gif)

**Expected behaviour**

I'd expect for the line-height to remain constant.

**Comment by JosephMcc** [comment] 2020-12-28 17:07
Thanks for the report. While I can reproduce this it's unlikely we can do anything to change it. It is the behavior of the GtkTextView widget that Xed uses and we really don't control.

**Comment by janos-r** [comment] 2020-12-28 18:09
Upon reading this, I check this on my 2 machines, one running 19.3 the other 20.0 and I can confirm that this happens only on the 20.0, not on 19.3. It's not horrible, but a little unfortunate. I don't know why, but I hope that there is a know reason for this "new" (?) GtkTextView behavior.

**Comment by JosephMcc** [comment] 2020-12-28 18:56
I did a quick test here just to be sure. This is also reproducible in Gedit and Gnome builder which are built around the same widgets as Xed. I'm going to go ahead and close this because the problem looks to be upstream and out of our hands.

**Closed by JosephMcc** 2020-12-28 18:56 UTC
