### ISSUE TITLE
hotkeys for changing text size not working

### ISSUE THREAD

**Issue by ivanixgames** [linuxmint/xed#333] opened 2019-11-01 04:54 UTC
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
The hot keys defined for increasing or decreasing text size do not work.
Instead the characters are inserted into the text.

**Steps to reproduce**
1) open a text file
2) Try Control+=  key combo.
3) See = inserted somewhere in text file

**Expected behaviour**
Text size should increase

**Other information**
xed 2.2.3 on Mint 19.1

**Comment by collinss** [comment] 2019-11-28 05:24
I can't reproduce this. Ctrl+= increases the text size like I'd expect.

**Comment by icarter09** [comment] 2019-12-15 04:32
Linux Mint 19.2 64bit
Xed 2.2.3

I agree with @collinss. I can not reproduce this issue either.

**Comment by collinss** [comment] 2019-12-15 15:53
Closing, as there's insufficient information to diagnose the problem.

**Closed by collinss** 2019-12-15 15:53 UTC
